### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by applech666** [FACEGOOD/Audio2Face#7]
(tensor1.15) research@research:~/disk1/Audio2Face-main/code/test/AiSpeech$ python zsmeif.py
Traceback (most recent call last):
  File "zsmeif.py", line 79, in <module>
    from lib.tensorflow.input_wavdata_output_lpc import c_lpc, get_audio_frames
  File "/home/research/disk1/Audio2Face-main/code/test/AiSpeech/lib/tensorflow/input_wavdata_output_lpc.py", line 20, in <module>
    dll = cdll.LoadLibrary(dll_path_linux)
  File "/home/research/disk1/anaconda3/envs/tensor1.15/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/research/disk1/anaconda3/envs/tensor1.15/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/research/disk1/Audio2Face-main/code/test/AiSpeech/lib/tensorflow/LPC.dll: invalid ELF header

**Comment by SZNero** [comment]
The test is only support in Windows platform.

**Comment by applech666** [comment]
thanks！

**Comment by wukl001** [comment]
> 该测试仅在 Windows 平台中受支持。
不可在Linux服务器上使用吗？
